_welcome:
    pattern:  /
    defaults: { _controller: StartupSchoolPhpInTheCloudBundle:Welcome:index }

_blog:
    resource: "@StartupSchoolPhpInTheCloudBundle/Controller/BlogController.php"
    type:     annotation
    prefix:   /blog

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
